export default {
    something_went_wrong: 'Something went wrong!',
    oops: 'Oops!',
    loading: 'Loading...',
    retry: 'Retry',
    back: 'Back',
    SignUpForFree: 'Sign up for free',
    ContinueWithEmail: 'Continue with Email',
    HyperhireAssignment: 'Hyperhire\nAssignment',
    CreateAccount: 'Create Account',
    CompetitionToSignUp: 'Competition to sign up *',
    YouMustPickACompetitionToRegister: 'You must pick a competition to register',
    EmailFormatIsInvalid: 'Email format is invalid',
    AtLeast8Letters: 'At least 8 letters',
    IncludeAtLeast3UppercaseLettersLowercaseLettersNumberOrSpecialLetters:
        'Include at least 3 uppercase letters, lowercase letters, number, or special letters',
    SpecialChars: 'Special letters are only limited to (~`!@#$%^&*()_-+=?)',
    PasswordNotMatch: 'New password and Confirm password do not match.',
    FieldRequired: 'This is a required field.',
    Password: 'New Password',
    ConfirmPassword: 'Confirm Password',
    FirstName: 'First Name in English *',
    LastName: 'Last Name in English *',
    SignUp: 'Sign Up',
    Competition: 'Competition',
    CompetitionDescription:
        'An account is needed per one host. If you already have an account for the host of competition you want to sign up, you can login and  register.',
    Welcome: 'Welcome to Hyperhire',
    GreatToHaveYouWithUs: 'Great to have you with us!',
    GotIt: 'Got It',
    LogOut: 'Log Out',
};
