export default {
    IC_HYPERHIRE: require('./imageFile/ic_hyperhire.png'),
    IC_SEARCH: require('./imageFile/ic_search.png'),
    IMG_ERROR: require('./imageFile/img_error.png'),
    IC_SHINE: require('./imageFile/ic_shine.png'),
    IC_ARROW_LEFT: require('./imageFile/ic_arrow_left.png'),
    IC_ARROW_LEFT_2: require('./imageFile/ic_arrow_left_2.png'),
    IC_ARROW_RIGHT: require('./imageFile/ic_arrow_right.png'),
    IC_CLOSE: require('./imageFile/ic_close.png'),
    IC_DROPDOWN: require('./imageFile/ic_dropdown.png'),
    IC_EYE: require('./imageFile/ic_eye.png'),
    IC_EYE_OPEN: require('./imageFile/ic_eye_open.png'),
    IC_EYE_CLOSE: require('./imageFile/ic_eye_close.png'),
    IC_LOGIN: require('./imageFile/ic_login.png'),
    IC_MAIL: require('./imageFile/ic_mail.png'),
    IC_CHECK: require('./imageFile/ic_check.png'),
    IC_UNCHECK: require('./imageFile/ic_uncheck.png'),
    IMG_FLOWERS: require('./imageFile/img_flowers.png'),
};
